# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/client-oauth-discovery-dui/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "thursday"
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/lyo-client-samples/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "thursday"
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/oauth-twolegged-sample/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "thursday"
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "thursday"