# Smoke testing client samples on Jazz sandbox instances

name: Smoke testing

on:
#  push:
#    branches: [main]
  schedule:
    - cron: "11 04 * * 4" # catch SNAPSHOT breaking changes
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-smoke
  cancel-in-progress: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'ci:full') }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Build Lyo Client samples
        run: |
          mvn -B clean verify --file lyo-client-samples/pom.xml
      - name: E2E client samples tests on ELM @ Jazz.net
        run: ./bin/test-jazz_net.sh
        env:
          JAZZ_NET_USERNAME: ${{ secrets.JAZZ_NET_USERNAME }}
          JAZZ_NET_PASSWORD: ${{ secrets.JAZZ_NET_PASSWORD }}
      # - name: E2E client samples tests on ELM @ IBM Nordic
      #   run: ./bin/test-jazz_nordic.sh
      #   env:
      #     JAZZ_NORDIC_USERNAME: ${{ secrets.JAZZ_NORDIC_USERNAME }}
      #     JAZZ_NORDIC_PASSWORD: ${{ secrets.JAZZ_NORDIC_PASSWORD }}
#      CRJAZ2398I The user has a "Practitioner-Floating" client access license assigned that would normally allow this operation, but the license expired on 01-Oct-2024 00:00.
#      - name: E2E client samples tests on ELM @ KTH
#        run: ./bin/test-jazz_kth.sh
#        env:
#          JAZZ_ITM_USERNAME: ${{ secrets.JAZZ_ITM_USERNAME }}
#          JAZZ_ITM_PASSWORD: ${{ secrets.JAZZ_ITM_PASSWORD }}
