name: "CI (OAuth two-legged sample)"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/**'
      - 'oauth-twolegged-sample/**'
  schedule:
    - cron: "01 13 1-7 * 5" # catch SNAPSHOT breaking changes
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'ci:full') }}

jobs:
  build-oauth-legacy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # EOL in 2030 for Azul JDK 1.8
          java-version: '8'
      - name: Build OAuth Two-legged samples
        run: |
          mvn -B clean verify --file oauth-twolegged-sample/oauth.sample/pom.xml
          mvn -B clean verify --file oauth-twolegged-sample/oauth-cli-helper/pom.xml
