# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "30 4 * * 5" # catch SNAPSHOT breaking changes
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: [17]
        distribution: ['temurin', 'zulu', 'oracle', 'corretto', 'microsoft', 'liberica']
        include:
          - java-version: '11'
            distribution: temurin
            experimental: true
          - java-version: '20'
            distribution: zulu
            experimental: true
          - java-version: '21-ea'
            distribution: zulu
            experimental: true
          - java-version: '21-ea'
            distribution: temurin
            experimental: true
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution:  ${{ matrix.distribution }}
          java-version: ${{ matrix.java-version }}
      - name: Build Lyo Client samples
        run: |
          mvn -B clean verify --file lyo-client-samples/pom.xml

  build-legacy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # EOL in 2030 for Azul JDK 1.8
          java-version: 8
      - name: Build OAuth Discovery application
        run: |
          mvn -B clean verify --file client-oauth-discovery-dui/pom.xml
      - name: Build OAuth Two-legged samples
        run: |
          mvn -B clean verify --file oauth-twolegged-sample/oauth.sample/pom.xml
          mvn -B clean verify --file oauth-twolegged-sample/oauth-cli-helper/pom.xml
